In [ ]:
import pypsa
from pypsa.common import annuity
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import plotly.io as pio
import plotly.offline as py

pd.options.plotting.backend = "plotly"

# Render static PNG images so plots are visible on GitHub
pio.renderers.default = "png"

## Read preprocessed Data

In [240]:
data_cost : str = "data/costs_2030.csv"


costs = pd.read_csv(data_cost, index_col=[0, 1])

costs.loc[costs.unit.str.contains("/kW"), "value"] *= 1e3
costs.unit = costs.unit.str.replace("/kW", "/MW")

defaults = {
    "FOM": 0,
    "VOM": 0,
    "efficiency": 1,
    "fuel": 0,
    "investment": 0,
    "lifetime": 25,
    "CO2 intensity": 0,
    "discount rate": 0.07,
}

costs = costs.value.unstack().fillna(defaults)
costs.at["OCGT", "fuel"] = costs.at["gas", "fuel"]
costs.at["CCGT", "fuel"] = costs.at["gas", "fuel"]
costs.at["OCGT", "CO2 intensity"] = costs.at["gas", "CO2 intensity"]
costs.at["CCGT", "CO2 intensityuel"] = costs.at["gas", "CO2 intensity"]

costs.rename(index={"onwind": "wind", "solar": "pv"}, inplace=True)


discount_rate = 0.07
lifetime = 20

annuity_factor = annuity(discount_rate, lifetime)


costs["marginal_cost"] = costs["VOM"] + costs["fuel"] / costs["efficiency"]
costs["capital_cost"] = (annuity_factor + costs["FOM"] / 100 ) * costs["investment"]

/var/folders/c2/0pncj6ld4glby0b51j0k8dgc0000gn/T/ipykernel_4471/1558647293.py:32: DeprecatedWarning:

annuity is deprecated as of 1.1.0 and will be removed in 2.0.0. Use pypsa.costs.annuity() instead.

In [241]:
timeseries_path = "data/timeseries_2025_germany.csv"

timeseries = pd.read_csv(timeseries_path, index_col=0, parse_dates=True)

In [242]:
timeseries.resample("4h").first()

,load_Nord,load_West,load_Ost,load_Süd,wind_Nord,wind_West,wind_Ost,wind_Süd,pv_Nord,pv_West,pv_Ost,pv_Süd
time,,,,,,,,,,,,
2025-01-01 00:00:00,8519.080950,15145.032800,9465.645500,14198.468250,0.989543,0.749514,0.850072,0.240686,0.000000,0.000000,0.000000,0.000000
2025-01-01 04:00:00,7966.970550,14163.503200,8852.189500,13278.284250,0.998344,0.822706,0.928523,0.328637,0.000000,0.000000,0.000000,0.000000
2025-01-01 08:00:00,8665.275600,15404.934400,9628.084000,14442.126000,0.951009,0.921379,0.955833,0.419579,0.000034,0.000000,0.008245,0.067405
2025-01-01 12:00:00,9427.708800,16760.371200,10475.232000,15712.848000,0.896804,0.889816,0.972782,0.446723,0.037500,0.275686,0.231281,0.514126
2025-01-01 16:00:00,10135.511100,18018.686400,11261.679000,16892.518500,0.999977,0.989557,0.995142,0.588582,0.000000,0.004053,0.000000,0.019459
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-31 04:00:00,9230.250801,16409.334757,10255.834223,15383.751335,0.556287,0.113664,0.331164,0.046102,0.000000,0.000000,0.000000,0.000000
2025-12-31 08:00:00,9230.250801,16409.334757,10255.834223,15383.751335,0.737223,0.163983,0.471398,0.078796,0.001038,0.000000,0.041102,0.072906
2025-12-31 12:00:00,9230.250801,16409.334757,10255.834223,15383.751335,0.620009,0.241881,0.721611,0.122856,0.118339,0.200982,0.030758,0.388230
2025-12-31 16:00:00,9230.250801,16409.334757,10255.834223,15383.751335,0.505317,0.328002,0.678698,0.234569,0.000000,0.000923,0.000000,0.015748
2025-12-31 20:00:00,9230.250801,16409.334757,10255.834223,15383.751335,0.524359,0.352470,0.472289,0.252518,0.000000,0.000000,0.000000,0.000000

In [243]:
timeseries.columns

Index(['load_Nord', 'load_West', 'load_Ost', 'load_Süd', 'wind_Nord',
       'wind_West', 'wind_Ost', 'wind_Süd', 'pv_Nord', 'pv_West', 'pv_Ost',
       'pv_Süd'],
      dtype='str')

### 4 Zone Model Initialisation

In [244]:
network = pypsa.Network()

In [245]:
carriers = [
    "wind", 
    "pv", # solar
    "OCGT",  # open cycle gas turbine
    "hydrogen storage underground",
    "battery storage",
    "electricity",
]

colors={
    "wind": "dodgerblue",
    "pv": "gold",
    "OCGT": "indianred",
    "hydrogen storage underground": "magenta",
    "battery storage": "yellowgreen",
    "electricity":  "black"}


for carrier in carriers:
    network.add(
        "Carrier",
        name= carrier,
        color = colors[carrier],
        
        co2_emissions = costs.at[carrier, "CO2 intensity"] if carrier in costs.index else 0,
        overwrite=True
        
    )

In [246]:
network.carriers

,co2_emissions,color,nice_name,max_growth,max_relative_growth
name,,,,,
wind,0.000,dodgerblue,,inf,0.0
pv,0.000,gold,,inf,0.0
OCGT,0.198,indianred,,inf,0.0
hydrogen storage underground,0.000,magenta,,inf,0.0
battery storage,0.000,yellowgreen,,inf,0.0
electricity,0.000,black,,inf,0.0

### Adding Buses

In [247]:
regions = ["Nord", "West", "Ost", "Süd"]

for region in regions:
    network.add(
        "Bus",
        name = f"Bus_{region}",
        type = "electricity",
        carrier = 'electricity',
        overwrite=True
    )

In [248]:
network.snapshots = timeseries.index
network.snapshots

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 01:00:00',
               '2025-01-01 02:00:00', '2025-01-01 03:00:00',
               '2025-01-01 04:00:00', '2025-01-01 05:00:00',
               '2025-01-01 06:00:00', '2025-01-01 07:00:00',
               '2025-01-01 08:00:00', '2025-01-01 09:00:00',
               ...
               '2025-12-31 14:00:00', '2025-12-31 15:00:00',
               '2025-12-31 16:00:00', '2025-12-31 17:00:00',
               '2025-12-31 18:00:00', '2025-12-31 19:00:00',
               '2025-12-31 20:00:00', '2025-12-31 21:00:00',
               '2025-12-31 22:00:00', '2025-12-31 23:00:00'],
              dtype='datetime64[us]', name='snapshot', length=8760, freq=None)

In [249]:
network.buses

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network
name,,,,,,,,,,,,,
Bus_Nord,1.0,electricity,0.0,0.0,electricity,,,1.0,0.0,inf,PQ,,
Bus_West,1.0,electricity,0.0,0.0,electricity,,,1.0,0.0,inf,PQ,,
Bus_Ost,1.0,electricity,0.0,0.0,electricity,,,1.0,0.0,inf,PQ,,
Bus_Süd,1.0,electricity,0.0,0.0,electricity,,,1.0,0.0,inf,PQ,,

In [250]:
network.snapshot_weightings.loc[:,:] = 4

### Adding Load

In [251]:
regions = ["Nord", "West", "Ost", "Süd"]
for region in regions:
    network.add(
        "Load",
        f"Demand_{region}",
        bus=f"Bus_{region}",
        p_set= timeseries[f"load_{region}"],
        carrier = "electricity",
        overwrite=True
    )

In [252]:
network.loads_t

{'p_set': name                 Demand_Nord   Demand_West    Demand_Ost    Demand_Süd
 snapshot
 2025-01-01 00:00:00  8519.080950  15145.032800   9465.645500  14198.468250
 2025-01-01 01:00:00  8323.858350  14797.970400   9248.731500  13873.097250
 2025-01-01 02:00:00  8109.321750  14416.572000   9010.357500  13515.536250
 2025-01-01 03:00:00  7928.587350  14095.266400   8809.541500  13214.312250
 2025-01-01 04:00:00  7966.970550  14163.503200   8852.189500  13278.284250
 ...                          ...           ...           ...           ...
 2025-12-31 19:00:00  9230.250801  16409.334757  10255.834223  15383.751335
 2025-12-31 20:00:00  9230.250801  16409.334757  10255.834223  15383.751335
 2025-12-31 21:00:00  9230.250801  16409.334757  10255.834223  15383.751335
 2025-12-31 22:00:00  9230.250801  16409.334757  10255.834223  15383.751335
 2025-12-31 23:00:00  9230.250801  16409.334757  10255.834223  15383.751335

 [8760 rows x 4 columns],
 'q_set': Empty DataFrame
 Columns: []
 Index: [2025-01-01 00:00:00, 2025-01-01 01:00:00, 2025-01-01 02:00:00, 2025-01-01 03:00:00, 2025-01-01 04:00:00, 2025-01-01 05:00:00, 2025-01-01 06:00:00, 2025-01-01 07:00:00, 2025-01-01 08:00:00, 2025-01-01 09:00:00, 2025-01-01 10:00:00, 2025-01-01 11:00:00, 2025-01-01 12:00:00, 2025-01-01 13:00:00, 2025-01-01 14:00:00, 2025-01-01 15:00:00, 2025-01-01 16:00:00, 2025-01-01 17:00:00, 2025-01-01 18:00:00, 2025-01-01 19:00:00, 2025-01-01 20:00:00, 2025-01-01 21:00:00, 2025-01-01 22:00:00, 2025-01-01 23:00:00, 2025-01-02 00:00:00, 2025-01-02 01:00:00, 2025-01-02 02:00:00, 2025-01-02 03:00:00, 2025-01-02 04:00:00, 2025-01-02 05:00:00, 2025-01-02 06:00:00, 2025-01-02 07:00:00, 2025-01-02 08:00:00, 2025-01-02 09:00:00, 2025-01-02 10:00:00, 2025-01-02 11:00:00, 2025-01-02 12:00:00, 2025-01-02 13:00:00, 2025-01-02 14:00:00, 2025-01-02 15:00:00, 2025-01-02 16:00:00, 2025-01-02 17:00:00, 2025-01-02 18:00:00, 2025-01-02 19:00:00, 2025-01-02 20:00:00, 2025-01-02 21:00:00, 2025-01-02 22:00:00, 2025-01-02 23:00:00, 2025-01-03 00:00:00, 2025-01-03 01:00:00, 2025-01-03 02:00:00, 2025-01-03 03:00:00, 2025-01-03 04:00:00, 2025-01-03 05:00:00, 2025-01-03 06:00:00, 2025-01-03 07:00:00, 2025-01-03 08:00:00, 2025-01-03 09:00:00, 2025-01-03 10:00:00, 2025-01-03 11:00:00, 2025-01-03 12:00:00, 2025-01-03 13:00:00, 2025-01-03 14:00:00, 2025-01-03 15:00:00, 2025-01-03 16:00:00, 2025-01-03 17:00:00, 2025-01-03 18:00:00, 2025-01-03 19:00:00, 2025-01-03 20:00:00, 2025-01-03 21:00:00, 2025-01-03 22:00:00, 2025-01-03 23:00:00, 2025-01-04 00:00:00, 2025-01-04 01:00:00, 2025-01-04 02:00:00, 2025-01-04 03:00:00, 2025-01-04 04:00:00, 2025-01-04 05:00:00, 2025-01-04 06:00:00, 2025-01-04 07:00:00, 2025-01-04 08:00:00, 2025-01-04 09:00:00, 2025-01-04 10:00:00, 2025-01-04 11:00:00, 2025-01-04 12:00:00, 2025-01-04 13:00:00, 2025-01-04 14:00:00, 2025-01-04 15:00:00, 2025-01-04 16:00:00, 2025-01-04 17:00:00, 2025-01-04 18:00:00, 2025-01-04 19:00:00, 2025-01-04 20:00:00, 2025-01-04 21:00:00, 2025-01-04 22:00:00, 2025-01-04 23:00:00, 2025-01-05 00:00:00, 2025-01-05 01:00:00, 2025-01-05 02:00:00, 2025-01-05 03:00:00, ...]

 [8760 rows x 0 columns],
 'p': Empty DataFrame
 Columns: []
 Index: [2025-01-01 00:00:00, 2025-01-01 01:00:00, 2025-01-01 02:00:00, 2025-01-01 03:00:00, 2025-01-01 04:00:00, 2025-01-01 05:00:00, 2025-01-01 06:00:00, 2025-01-01 07:00:00, 2025-01-01 08:00:00, 2025-01-01 09:00:00, 2025-01-01 10:00:00, 2025-01-01 11:00:00, 2025-01-01 12:00:00, 2025-01-01 13:00:00, 2025-01-01 14:00:00, 2025-01-01 15:00:00, 2025-01-01 16:00:00, 2025-01-01 17:00:00, 2025-01-01 18:00:00, 2025-01-01 19:00:00, 2025-01-01 20:00:00, 2025-01-01 21:00:00, 2025-01-01 22:00:00, 2025-01-01 23:00:00, 2025-01-02 00:00:00, 2025-01-02 01:00:00, 2025-01-02 02:00:00, 2025-01-02 03:00:00, 2025-01-02 04:00:00, 2025-01-02 05:00:00, 2025-01-02 06:00:00, 2025-01-02 07:00:00, 2025-01-02 08:00:00, 2025-01-02 09:00:00, 2025-01-02 10:00:00, 2025-01-02 11:00:00, 2025-01-02 12:00:00, 2025-01-02 13:00:00, 2025-01-02 14:00:00, 2025-01-02 15:00:00, 2025-01-02 16:00:00, 2025-01-02 17:00:00, 2025-01-02 18:00:00, 2025-01-02 19:00:00, 2025-01-02 20:00:00, 2025-01-02 21:00:00, 2025-01-02 22:00:00, 2025-01-02 23:00:00, 2025-01-03 00:00:00, 2025-01-03 01:00:00, 2025-01-03 02:00:00, 2025-01-03 03:00:00, 2025-01-03 04:00:00, 2025-01-03 05:00:00, 2025-01-03 06:00:00, 2025-01-03 07:00:00, 2025-01-03 08:00:00, 2025-01-03 09:00:00, 2025-01-03 10:00:00, 2025-01-03 11:00:00, 2025-01-03 12:00:00, 2025-01-03 13:00:00, 2025-01-03 14:00:00, 2025-01-03 15:00:00, 2025-01-03 16:00:00, 2025-01-03 17:00:00, 2025-01-03 18:00:00, 2025-01-03 19:00:00, 2025-01-03 20:00:00, 2025-01-03 21:00:00, 2025-01-03 22:00:00, 2025-01-03 23:00:00, 2025-01-04 00:00:00, 2025-01-04 01:00:00, 2025-01-04 02:00:00, 2025-01-04 03:00:00, 2025-01-04 04:00:00, 2025-01-04 05:00:00, 2025-01-04 06:00:00, 2025-01-04 07:00:00, 2025-01-04 08:00:00, 2025-01-04 09:00:00, 2025-01-04 10:00:00, 2025-01-04 11:00:00, 2025-01-04 12:00:00, 2025-01-04 13:00:00, 2025-01-04 14:00:00, 2025-01-04 15:00:00, 2025-01-04 16:00:00, 2025-01-04 17:00:00, 2025-01-04 18:00:00, 2025-01-04 19:00:00, 2025-01-04 20:00:00, 2025-01-04 21:00:00, 2025-01-04 22:00:00, 2025-01-04 23:00:00, 2025-01-05 00:00:00, 2025-01-05 01:00:00, 2025-01-05 02:00:00, 2025-01-05 03:00:00, ...]

 [8760 rows x 0 columns],
 'q': Empty DataFrame
 Columns: []
 Index: [2025-01-01 00:00:00, 2025-01-01 01:00:00, 2025-01-01 02:00:00, 2025-01-01 03:00:00, 2025-01-01 04:00:00, 2025-01-01 05:00:00, 2025-01-01 06:00:00, 2025-01-01 07:00:00, 2025-01-01 08:00:00, 2025-01-01 09:00:00, 2025-01-01 10:00:00, 2025-01-01 11:00:00, 2025-01-01 12:00:00, 2025-01-01 13:00:00, 2025-01-01 14:00:00, 2025-01-01 15:00:00, 2025-01-01 16:00:00, 2025-01-01 17:00:00, 2025-01-01 18:00:00, 2025-01-01 19:00:00, 2025-01-01 20:00:00, 2025-01-01 21:00:00, 2025-01-01 22:00:00, 2025-01-01 23:00:00, 2025-01-02 00:00:00, 2025-01-02 01:00:00, 2025-01-02 02:00:00, 2025-01-02 03:00:00, 2025-01-02 04:00:00, 2025-01-02 05:00:00, 2025-01-02 06:00:00, 2025-01-02 07:00:00, 2025-01-02 08:00:00, 2025-01-02 09:00:00, 2025-01-02 10:00:00, 2025-01-02 11:00:00, 2025-01-02 12:00:00, 2025-01-02 13:00:00, 2025-01-02 14:00:00, 2025-01-02 15:00:00, 2025-01-02 16:00:00, 2025-01-02 17:00:00, 2025-01-02 18:00:00, 2025-01-02 19:00:00, 2025-01-02 20:00:00, 2025-01-02 21:00:00, 2025-01-02 22:00:00, 2025-01-02 23:00:00, 2025-01-03 00:00:00, 2025-01-03 01:00:00, 2025-01-03 02:00:00, 2025-01-03 03:00:00, 2025-01-03 04:00:00, 2025-01-03 05:00:00, 2025-01-03 06:00:00, 2025-01-03 07:00:00, 2025-01-03 08:00:00, 2025-01-03 09:00:00, 2025-01-03 10:00:00, 2025-01-03 11:00:00, 2025-01-03 12:00:00, 2025-01-03 13:00:00, 2025-01-03 14:00:00, 2025-01-03 15:00:00, 2025-01-03 16:00:00, 2025-01-03 17:00:00, 2025-01-03 18:00:00, 2025-01-03 19:00:00, 2025-01-03 20:00:00, 2025-01-03 21:00:00, 2025-01-03 22:00:00, 2025-01-03 23:00:00, 2025-01-04 00:00:00, 2025-01-04 01:00:00, 2025-01-04 02:00:00, 2025-01-04 03:00:00, 2025-01-04 04:00:00, 2025-01-04 05:00:00, 2025-01-04 06:00:00, 2025-01-04 07:00:00, 2025-01-04 08:00:00, 2025-01-04 09:00:00, 2025-01-04 10:00:00, 2025-01-04 11:00:00, 2025-01-04 12:00:00, 2025-01-04 13:00:00, 2025-01-04 14:00:00, 2025-01-04 15:00:00, 2025-01-04 16:00:00, 2025-01-04 17:00:00, 2025-01-04 18:00:00, 2025-01-04 19:00:00, 2025-01-04 20:00:00, 2025-01-04 21:00:00, 2025-01-04 22:00:00, 2025-01-04 23:00:00, 2025-01-05 00:00:00, 2025-01-05 01:00:00, 2025-01-05 02:00:00, 2025-01-05 03:00:00, ...]

 [8760 rows x 0 columns]}

In [253]:
network.loads_t.p_set.plot(labels=dict(value = "Load MW"))
# plt.ylabel("Load [MW]")

### Adding Generators

In [254]:
regions = ["Nord", "West", "Ost", "Süd"]
generators = ["wind", "pv", "OCGT"]

for region in regions:
    for generator in generators:
        network.add(
            "Generator",
            name=f"{generator}_{region}",
            bus=f"Bus_{region}",
            carrier=generator,
            p_max_pu=timeseries[f"{generator}_{region}"] if generator != "OCGT" else 1.0,
            marginal_cost=costs.at[generator, "marginal_cost"],
            capital_cost=costs.at[generator, "capital_cost"],
            p_nom_extendable=True,
            overwrite=True
        )

In [255]:
network.generators_t.p_max_pu[:5]

name,wind_Nord,pv_Nord,wind_West,pv_West,wind_Ost,pv_Ost,wind_Süd,pv_Süd
snapshot,,,,,,,,
2025-01-01 00:00:00,0.989543,0.0,0.749514,0.0,0.850072,0.0,0.240686,0.0
2025-01-01 01:00:00,0.992777,0.0,0.779992,0.0,0.861112,0.0,0.257526,0.0
2025-01-01 02:00:00,0.995757,0.0,0.798748,0.0,0.887177,0.0,0.277494,0.0
2025-01-01 03:00:00,0.995413,0.0,0.819556,0.0,0.911713,0.0,0.307796,0.0
2025-01-01 04:00:00,0.998344,0.0,0.822706,0.0,0.928523,0.0,0.328637,0.0

In [256]:
network.generators_t.p_max_pu.loc["2025-06"].plot(labels=dict(value="Capacity Factor [p.u.]"))

### Adding Transmission Lines

In [257]:
lines = {
    "Nord_to_West": ("Bus_Nord", "Bus_West", 300),
    "Nord_to_Ost":  ("Bus_Nord", "Bus_Ost",  400),
    "West_to_Süd":  ("Bus_West", "Bus_Süd",  500),
    "Ost_to_Süd":   ("Bus_Ost",  "Bus_Süd",  400),
}

for name, (bus0, bus1, length) in lines.items():
    network.add(
        "Line",
        name=name,
        bus0=bus0,
        bus1=bus1,
        type="Al/St 240/40 4-bundle 380.0",
        length=length,
        s_nom=2000,
        s_nom_extendable=True,
        overwrite=True
    )

In [258]:
network.calculate_dependent_values()
network.lines

,bus0,bus1,type,x,r,g,b,s_nom,s_nom_mod,s_nom_extendable,...,v_ang_max,sub_network,x_pu,r_pu,g_pu,b_pu,x_pu_eff,r_pu_eff,s_nom_opt,v_nom
name,,,,,,,,,,,,,,,,,,,,,
Nord_to_West,Bus_Nord,Bus_West,Al/St 240/40 4-bundle 380.0,73.8,9.0,0.0,0.001301,2000.0,0.0,True,...,inf,,73.8,9.0,0.0,0.001301,73.8,9.0,0.0,1.0
Nord_to_Ost,Bus_Nord,Bus_Ost,Al/St 240/40 4-bundle 380.0,98.4,12.0,0.0,0.001734,2000.0,0.0,True,...,inf,,98.4,12.0,0.0,0.001734,98.4,12.0,0.0,1.0
West_to_Süd,Bus_West,Bus_Süd,Al/St 240/40 4-bundle 380.0,123.0,15.0,0.0,0.002168,2000.0,0.0,True,...,inf,,123.0,15.0,0.0,0.002168,123.0,15.0,0.0,1.0
Ost_to_Süd,Bus_Ost,Bus_Süd,Al/St 240/40 4-bundle 380.0,98.4,12.0,0.0,0.001734,2000.0,0.0,True,...,inf,,98.4,12.0,0.0,0.001734,98.4,12.0,0.0,1.0

### Adding StorageUnits (Batterie, Hydro Storage)

In [259]:
regions = ["Nord", "West", "Ost", "Süd"]
capital_cost_batterie = costs.at["battery inverter", "capital_cost"] 
+ 4 * costs.at["battery storage", "capital_cost"]

capital_costs_hydro_storage = (
costs.at["electrolysis", "capital_cost"]
+ costs.at["fuel cell", "capital_cost"]
+ 168 * costs.at["hydrogen storage underground", "capital_cost"]
)

for region in regions:
    network.add(
        "StorageUnit",
        name = f"BatteryStorage_{region}",
        carrier= "battery storage",
        bus=f"Bus_{region}",
        max_hours = 4,
        capital_cost = capital_cost_batterie,   
        efficiency_store=costs.at["battery inverter", "efficiency"],
        efficiency_dispatch=costs.at["battery inverter", "efficiency"],
        cyclic_state_of_charge=True, # the state of charge at the beginning of the optimisation period must equal the final state of charge.
        p_nom_extendable=True,
        overwrite=True
    )
    network.add(
        "StorageUnit",
        name = f"hydrogenStorage_{region}",
        bus=f"Bus_{region}",
        carrier="hydrogen storage underground",
        max_hours=168,
        capital_cost=capital_costs_hydro_storage,
        efficiency_store=costs.at["electrolysis", "efficiency"],
        efficiency_dispatch=costs.at["fuel cell", "efficiency"],
        p_nom_extendable=True,
        cyclic_state_of_charge=True,
        overwrite=True
    )

In [260]:
network.storage_units

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_nom_set,p_min_pu,...,state_of_charge_initial_per_period,state_of_charge_set,cyclic_state_of_charge,cyclic_state_of_charge_per_period,max_hours,efficiency_store,efficiency_dispatch,standing_loss,inflow,p_nom_opt
name,,,,,,,,,,,,,,,,,,,,,
BatteryStorage_Nord,Bus_Nord,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.9600,0.96,0.0,0.0,0.0
hydrogenStorage_Nord,Bus_Nord,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,168.0,0.6217,0.50,0.0,0.0,0.0
BatteryStorage_West,Bus_West,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.9600,0.96,0.0,0.0,0.0
hydrogenStorage_West,Bus_West,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,168.0,0.6217,0.50,0.0,0.0,0.0
BatteryStorage_Ost,Bus_Ost,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.9600,0.96,0.0,0.0,0.0
hydrogenStorage_Ost,Bus_Ost,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,168.0,0.6217,0.50,0.0,0.0,0.0
BatteryStorage_Süd,Bus_Süd,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,4.0,0.9600,0.96,0.0,0.0,0.0
hydrogenStorage_Süd,Bus_Süd,PQ,,0.0,0.0,True,0.0,inf,NaN,-1.0,...,False,NaN,True,False,168.0,0.6217,0.50,0.0,0.0,0.0

### Adding Emission Limits

In [261]:
# Moderate reduction scenario constant = 80e6    # 80 million tonnes

network.add(
    "GlobalConstraint",
    name="co2_limit",
    carrier_attribute="co2_emissions",
    sense="<=",
    constant= 80e6
    # constant=0,
)

### Consistency-Check

In [262]:

network.consistency_check()

### Model Run

In [263]:
network.optimize(solver_name="highs")

/var/folders/c2/0pncj6ld4glby0b51j0k8dgc0000gn/T/ipykernel_4471/3589273427.py:1: FutureWarning:

The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.

WARNING:pypsa.networks:Warning, sub network 0 is not electric but contains multiple buses
and branches. Passive flows are not allowed for non-electric networks!
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 18.10it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 83.59it/s]
INFO:linopy.io: Writing time: 1.24s

Running HiGHS 1.13.1 (git hash: 1d267d9): Copyright (c) 2026 under MIT licence terms
LP linopy-problem-1h14k83x has 814705 rows; 350424 cols; 1734986 nonzeros
Coefficient ranges:
  Matrix  [1e-07, 2e+06]
  Cost    [5e-02, 5e+05]
  Bound   [0e+00, 0e+00]
  RHS     [6e+03, 8e+07]
WARNING: Problem has some excessively large row bounds
WARNING:    Consider scaling the    bounds by 1e-2, or setting the user_bound_scale option to -7
Presolving model
412203 rows, 333382 cols, 1245366 nonzeros  1s
Dependent equations search running on 84488 equations with time limit of 1000.00s
Dependent equations search removed 0 rows and 0 nonzeros in 0.02s (limit = 1000.00s)
382811 rows, 303990 cols, 1224998 nonzeros  3s
Presolve reductions: rows 382811(-431894); columns 303990(-46434); nonzeros 1224998(-509988)
Solving the presolved LP
Using dual simplex solver
  Iteration        Objective     Infeasibilities num(sum)
          0     0.0000000000e+00 Pr: 14408(2.28943e+10); Du: 0(2.76324e-09) 4.5s
       1464     1.5057861472e+09 Pr: 67391(9.28174e+12); Du: 0(5.26327e-07) 10.7s
       7061     7.2953392856e+09 Pr: 41714(8.71895e+10); Du: 0(4.09142e-06) 18.5s
       9746     9.1685380053e+09 Pr: 16107(7.86449e+10); Du: 0(3.85223e-06) 23.9s
      11938     1.0680033839e+10 Pr: 15157(7.75798e+10); Du: 0(3.62475e-06) 30.8s
      14281     1.2308364454e+10 Pr: 67264(1.05477e+12); Du: 0(3.86882e-06) 37.6s
      16097     1.3184910461e+10 Pr: 24046(3.66756e+11); Du: 0(3.94546e-06) 43.9s
      18151     1.4039065618e+10 Pr: 23572(1.37929e+12); Du: 0(4.43028e-06) 49.4s
      20553     1.4676152114e+10 Pr: 23389(1.01464e+12); Du: 0(4.1572e-06) 56.2s
      23043     1.5026166870e+10 Pr: 41164(8.41325e+11); Du: 0(4.7385e-06) 62.6s
      24304     1.5455838439e+10 Pr: 40465(5.21122e+13); Du: 0(5.10917e-06) 69.0s
      29941     1.6032305052e+10 Pr: 40592(1.24618e+13); Du: 0(6.10272e-06) 74.0s
      35676     1.6644797588e+10 Pr: 40519(4.68142e+13); Du: 0(7.14719e-06) 80.9s
      41162     1.7019243805e+10 Pr: 39631(8.50949e+12); Du: 0(6.51894e-06) 86.1s
      44602     1.7409202364e+10 Pr: 40103(7.46315e+12); Du: 0(7.19083e-06) 92.0s
      50303     1.7971859689e+10 Pr: 38876(1.70968e+13); Du: 0(8.05311e-06) 98.1s
      51956     1.8094690786e+10 Pr: 39764(9.01372e+14); Du: 0(8.16258e-06) 104.6s
      53010     2.0195095825e+10 Pr: 39784(5.44678e+14); Du: 0(8.42545e-06) 110.5s
      54413     2.1794441681e+10 Pr: 39776(5.90153e+14); Du: 0(8.40312e-06) 117.3s
      55559     2.1796948351e+10 Pr: 39793(5.92005e+14); Du: 0(8.16608e-06) 122.8s
      56671     2.2016220464e+10 Pr: 39887(5.90775e+14); Du: 0(8.18169e-06) 128.3s
      58055     2.4394589252e+10 Pr: 39968(1.04636e+15); Du: 0(8.18169e-06) 135.7s
      59610     2.5932271602e+10 Pr: 91225(3.926e+14); Du: 0(8.14011e-06) 144.3s
      60395     2.7608096400e+10 Pr: 74925(2.50949e+14); Du: 0(8.23891e-06) 150.1s
      63900     2.7840652084e+10 Pr: 74546(2.05752e+14); Du: 0(8.93286e-06) 156.0s
      66383     2.8408374703e+10 Pr: 73301(1.99433e+13); Du: 0(9.31865e-06) 163.8s
      67618     2.8788402277e+10 Pr: 73577(2.27172e+14); Du: 0(8.76938e-06) 170.7s
      69261     2.9157028699e+10 Pr: 50729(1.46211e+13); Du: 0(8.46616e-06) 177.9s
      74010     2.9348482349e+10 Pr: 76470(2.52924e+12); Du: 0(1.04194e-05) 185.0s
      77935     2.9555267620e+10 Pr: 151958(7.34679e+13); Du: 0(1.34338e-05) 191.4s
      81075     2.9700803523e+10 Pr: 51631(2.32778e+11); Du: 0(1.29085e-05) 201.4s
      82995     2.9813807729e+10 Pr: 52613(1.8532e+12); Du: 0(1.22679e-05) 207.0s
      85088     2.9855194000e+10 Pr: 90285(1.51293e+13); Du: 0(1.43174e-05) 212.5s
      88783     3.0005603265e+10 Pr: 63759(8.52304e+12); Du: 0(1.54944e-05) 220.0s
      91594     3.0078547707e+10 Pr: 104273(3.37319e+13); Du: 0(1.54986e-05) 228.7s
      97831     3.0104673200e+10 Pr: 128013(2.75872e+15); Du: 0(2.28105e-05) 236.4s
     101137     3.0194019346e+10 Pr: 102471(6.43663e+13); Du: 0(2.53722e-05) 246.3s
     102741     3.0204176518e+10 Pr: 56154(5.2806e+13); Du: 0(2.55561e-05) 251.5s
     104805     3.0230876245e+10 Pr: 88229(1.25743e+14); Du: 0(2.63634e-05) 260.5s
     106779     3.0244300634e+10 Pr: 129607(1.15737e+13); Du: 0(2.56065e-05) 269.2s
     107966     3.0245182006e+10 Pr: 95040(7.08974e+12); Du: 0(2.63957e-05) 274.7s
     110082     3.0260635475e+10 Pr: 59178(8.67256e+11); Du: 0(2.27035e-05) 283.6s
     112884     3.0285382463e+10 Pr: 98182(2.09466e+13); Du: 0(2.31988e-05) 293.4s
     120802     3.0353821847e+10 Pr: 111837(1.23347e+13); Du: 0(2.68627e-05) 302.2s
     123443     3.0374016930e+10 Pr: 95184(6.97232e+13); Du: 0(2.47978e-05) 311.4s
     125348     3.0374738977e+10 Pr: 27775(1.94705e+11); Du: 0(2.39303e-05) 320.9s
     127423     3.0395047669e+10 Pr: 54874(2.32421e+12); Du: 0(2.47684e-05) 330.1s
     129006     3.0407684025e+10 Pr: 69938(2.74197e+14); Du: 0(2.59073e-05) 336.3s
     130002     3.0446148548e+10 Pr: 37315(3.54846e+11); Du: 0(2.74719e-05) 341.8s
     133203     3.0462224040e+10 Pr: 111219(3.85068e+12); Du: 0(2.66762e-05) 350.8s
     134086     3.0481049703e+10 Pr: 120713(1.09568e+13); Du: 0(2.64279e-05) 356.4s
     134932     3.0510302150e+10 Pr: 148059(4.53301e+13); Du: 0(2.52586e-05) 361.6s
     136147     3.0523401554e+10 Pr: 94396(2.13758e+13); Du: 0(2.51313e-05) 367.5s
     137604     3.0527794981e+10 Pr: 104744(1.37443e+14); Du: 0(2.58633e-05) 373.1s
     139654     3.0564870528e+10 Pr: 64657(2.6177e+13); Du: 0(2.56234e-05) 382.7s
     141838     3.0568054024e+10 Pr: 39574(5.9481e+11); Du: 0(2.63659e-05) 388.8s
     161838     3.0568965375e+10 Pr: 141536(9.65088e+13); Du: 0(3.19903e-05) 394.8s
     162883     3.0569107299e+10 Pr: 115909(2.72919e+14); Du: 0(3.31012e-05) 401.9s
     163864     3.0569269969e+10 Pr: 89243(1.89903e+14); Du: 0(3.30639e-05) 408.2s
     164889     3.0571895756e+10 Pr: 91661(6.89826e+13); Du: 0(3.32895e-05) 414.0s
     165722     3.0572034893e+10 Pr: 90788(3.55804e+13); Du: 0(3.35681e-05) 419.1s
     166619     3.0572503880e+10 Pr: 115947(2.1511e+14); Du: 0(3.44716e-05) 424.6s
     167563     3.0572647126e+10 Pr: 64231(2.98553e+13); Du: 0(3.40939e-05) 430.5s
     168457     3.0572785536e+10 Pr: 58603(3.012e+12); Du: 0(3.4717e-05) 436.5s
     169538     3.0578738538e+10 Pr: 123400(5.28926e+13); Du: 0(3.53305e-05) 442.6s
     170430     3.0579455148e+10 Pr: 116559(9.68152e+13); Du: 0(3.45529e-05) 449.8s
     171439     3.0579765075e+10 Pr: 90099(1.30403e+14); Du: 0(3.38711e-05) 457.7s
     172354     3.0579920219e+10 Pr: 117072(2.46235e+14); Du: 0(3.44394e-05) 466.2s
     173314     3.0580749628e+10 Pr: 64792(6.04215e+13); Du: 0(3.41894e-05) 472.3s
     174206     3.0580861079e+10 Pr: 90912(2.97852e+14); Du: 0(3.40447e-05) 478.2s
     175125     3.0580986463e+10 Pr: 61613(6.6673e+11); Du: 0(3.40365e-05) 483.8s
     176427     3.0587861433e+10 Pr: 71480(3.00849e+13); Du: 0(3.58421e-05) 489.3s
     178261     3.0615205521e+10 Pr: 79780(3.27873e+13); Du: 0(3.4344e-05) 495.9s
     179143     3.0615684017e+10 Pr: 63680(4.30949e+13); Du: 0(3.46793e-05) 501.0s
     180824     3.0635721444e+10 Pr: 132865(2.56187e+14); Du: 0(3.57718e-05) 507.9s
     181786     3.0645587119e+10 Pr: 60672(1.01496e+12); Du: 0(3.60214e-05) 513.7s
     183045     3.0674274230e+10 Pr: 126011(8.1788e+13); Du: 0(3.64854e-05) 519.8s
     184141     3.0680872928e+10 Pr: 65053(1.11173e+14); Du: 0(3.81251e-05) 525.7s
     185084     3.0681224292e+10 Pr: 63105(5.86971e+12); Du: 0(3.76411e-05) 531.8s
     186978     3.0687777361e+10 Pr: 97790(1.08066e+13); Du: 0(3.67428e-05) 539.8s
     187904     3.0694823381e+10 Pr: 116383(4.54943e+12); Du: 0(3.63604e-05) 545.9s
     190274     3.0714093120e+10 Pr: 128265(2.30281e+13); Du: 0(3.71672e-05) 553.2s
     192182     3.0719707569e+10 Pr: 76088(2.69357e+12); Du: 0(3.6158e-05) 562.5s
     193508     3.0728867274e+10 Pr: 99135(3.05356e+12); Du: 0(3.67075e-05) 569.7s
     195387     3.0738496963e+10 Pr: 97731(1.04791e+13); Du: 0(3.79069e-05) 577.0s
     196777     3.0745179311e+10 Pr: 115931(2.02901e+12); Du: 0(3.71673e-05) 583.6s
     197942     3.0750752621e+10 Pr: 60830(8.79625e+11); Du: 0(3.69247e-05) 589.9s
     199239     3.0773069926e+10 Pr: 58246(4.11746e+12); Du: 0(3.61873e-05) 597.1s
     200638     3.0796174400e+10 Pr: 142403(6.59771e+13); Du: 0(3.5624e-05) 603.2s
     203676     3.0806190057e+10 Pr: 70617(1.78956e+12); Du: 0(3.58148e-05) 610.0s
     205895     3.0836739330e+10 Pr: 74581(8.34684e+11); Du: 0(3.36898e-05) 617.7s
     208630     3.0856271967e+10 Pr: 87381(2.49063e+13); Du: 0(3.59326e-05) 625.0s
     210544     3.0868204975e+10 Pr: 72955(8.30942e+12); Du: 0(3.67668e-05) 635.3s
     212889     3.0880643237e+10 Pr: 99630(5.51075e+13); Du: 0(3.67103e-05) 641.9s
     214930     3.0900353580e+10 Pr: 70493(1.62462e+12); Du: 0(3.58677e-05) 649.0s
     217160     3.0905229189e+10 Pr: 64926(1.20501e+12); Du: 0(3.46138e-05) 659.7s
     218274     3.0940164625e+10 Pr: 163464(4.23642e+13); Du: 0(3.50333e-05) 666.9s
     220121     3.0954331971e+10 Pr: 89746(3.23559e+12); Du: 0(3.45953e-05) 673.9s
     223010     3.1052123187e+10 Pr: 99936(2.29166e+14); Du: 0(3.74142e-05) 681.8s
     224750     3.1053867027e+10 Pr: 89355(1.63296e+13); Du: 0(3.66657e-05) 689.7s
     226255     3.1068628378e+10 Pr: 66231(3.93595e+12); Du: 0(3.69944e-05) 696.9s
     228737     3.1098729156e+10 Pr: 54041(5.58705e+13); Du: 0(3.59781e-05) 702.4s
     230550     3.1119293621e+10 Pr: 89889(8.26792e+12); Du: 0(3.67098e-05) 709.8s
     231815     3.1120481783e+10 Pr: 71191(1.36936e+12); Du: 0(3.67985e-05) 717.1s
     232958     3.1135146790e+10 Pr: 177612(7.10429e+13); Du: 0(3.53881e-05) 724.0s
     233885     3.1141313731e+10 Pr: 150411(3.31661e+14); Du: 0(3.60109e-05) 730.2s
     235214     3.1175105704e+10 Pr: 170499(2.59683e+15); Du: 0(3.54205e-05) 737.1s
     236090     3.1240767102e+10 Pr: 117952(1.15059e+13); Du: 0(3.56293e-05) 743.5s
     237144     3.1244458699e+10 Pr: 124175(4.28524e+12); Du: 0(3.45945e-05) 750.4s
     237942     3.1244531914e+10 Pr: 115802(3.34442e+13); Du: 0(3.51528e-05) 756.9s
     238768     3.1247837354e+10 Pr: 115181(6.36768e+13); Du: 0(3.61229e-05) 764.6s
     239742     3.1248154806e+10 Pr: 95490(3.6953e+12); Du: 0(3.5247e-05) 772.9s
     240610     3.1250092128e+10 Pr: 77526(2.50502e+12); Du: 0(3.44274e-05) 781.1s
     241838     3.1258500144e+10 Pr: 146842(1.25794e+14); Du: 0(3.39538e-05) 792.1s
     243287     3.1258709549e+10 Pr: 146900(1.08463e+14); Du: 0(3.61016e-05) 800.3s
     245172     3.1260020501e+10 Pr: 98539(1.11626e+13); Du: 0(3.63259e-05) 807.6s
     247016     3.1261907726e+10 Pr: 117315(1.19127e+13); Du: 0(3.47466e-05) 816.2s
     248129     3.1268944780e+10 Pr: 98059(3.687e+12); Du: 0(3.48997e-05) 824.0s
     250737     3.1280028664e+10 Pr: 31368(4.01878e+11); Du: 0(3.51084e-05) 832.0s
     252183     3.1284489443e+10 Pr: 52473(5.19488e+11); Du: 0(3.49106e-05) 840.0s
     253093     3.1284540454e+10 Pr: 94997(2.35545e+12); Du: 0(3.59899e-05) 847.4s
     254005     3.1284588950e+10 Pr: 152945(2.21703e+14); Du: 0(3.65302e-05) 854.5s
     254829     3.1284641346e+10 Pr: 94582(1.41166e+12); Du: 0(3.66347e-05) 862.3s
     255650     3.1284688083e+10 Pr: 146410(1.85438e+13); Du: 0(3.64598e-05) 868.6s
     256837     3.1288236070e+10 Pr: 68547(5.51006e+11); Du: 0(3.65582e-05) 874.7s
     259664     3.1335985316e+10 Pr: 69744(9.31864e+11); Du: 0(3.68326e-05) 881.5s
     261444     3.1340740422e+10 Pr: 29292(4.43802e+11); Du: 0(3.74263e-05) 888.9s
     262759     3.1373232735e+10 Pr: 56477(8.38879e+11); Du: 0(3.69038e-05) 896.2s
     265504     3.1382660138e+10 Pr: 101866(3.1205e+13); Du: 0(3.57991e-05) 904.1s
     266801     3.1411300799e+10 Pr: 87604(1.61405e+12); Du: 0(3.61164e-05) 911.3s
     267977     3.1427815676e+10 Pr: 106383(1.12203e+13); Du: 0(3.66324e-05) 917.9s
     269960     3.1465394614e+10 Pr: 99228(8.97165e+14); Du: 0(3.59311e-05) 925.9s
     272001     3.1478719565e+10 Pr: 122739(4.86829e+12); Du: 0(3.68179e-05) 933.5s
     273667     3.1517210607e+10 Pr: 82210(9.72077e+11); Du: 0(3.69846e-05) 941.5s
     275262     3.1517457902e+10 Pr: 81406(1.65093e+13); Du: 0(3.60368e-05) 949.5s
     277308     3.1535834704e+10 Pr: 109381(2.54276e+13); Du: 0(3.64916e-05) 958.8s
     278573     3.1540930101e+10 Pr: 136924(5.22286e+12); Du: 0(3.70331e-05) 967.7s
     279714     3.1551102809e+10 Pr: 107820(3.42059e+12); Du: 0(3.68005e-05) 975.5s
     280624     3.1556796843e+10 Pr: 161138(1.85596e+13); Du: 0(3.57007e-05) 982.6s
     281438     3.1557478965e+10 Pr: 79966(1.97617e+12); Du: 0(3.50424e-05) 991.6s
     282333     3.1557533920e+10 Pr: 77835(5.01163e+12); Du: 0(3.44661e-05) 998.8s
     283348     3.1561355555e+10 Pr: 101890(2.51366e+14); Du: 0(3.55975e-05) 1005.6s
     290026     3.1579501896e+10 Pr: 70504(1.19546e+14); Du: 0(3.62188e-05) 1057.3s
     309246     3.3453250325e+10 Pr: 95754(3.99626e+13); Du: 0(3.22518e-05) 1117.8s
     326410     3.4386349483e+10 Pr: 72542(2.05166e+12); Du: 0(3.18963e-05) 1170.5s
     341294     3.5374103173e+10 Pr: 109663(5.69938e+12); Du: 0(2.93791e-05) 1222.2s
     357539     3.6321821473e+10 Pr: 92477(2.22977e+12); Du: 0(2.94339e-05) 1276.0s
     373840     3.7281357588e+10 Pr: 67934(2.62847e+12); Du: 0(2.76642e-05) 1337.5s
     390794     3.8080991344e+10 Pr: 110945(7.72596e+12); Du: 0(3.39654e-05) 1392.0s
     408675     3.8910350117e+10 Pr: 63313(2.58598e+12); Du: 0(3.46339e-05) 1451.7s
     424047     3.9630875669e+10 Pr: 125099(1.03999e+14); Du: 0(3.60834e-05) 1507.9s
     440236     4.0534087607e+10 Pr: 44218(5.41501e+11); Du: 0(3.6025e-05) 1566.3s
     451916     4.1523273638e+10 Pr: 80637(4.6212e+13); Du: 0(3.47527e-05) 1621.1s
     470441     4.2275026541e+10 Pr: 26959(1.02433e+12); Du: 0(3.57458e-05) 1675.1s
     494214     4.3491039849e+10 Pr: 53674(1.09271e+13); Du: 0(3.8246e-05) 1726.8s
     523608     4.4274866550e+10 Pr: 88241(4.93831e+12); Du: 0(3.44042e-05) 1780.0s
     551652     4.6050724373e+10 Pr: 26859(1.80215e+12); Du: 0(4.08304e-05) 1834.0s
     574423     4.6741718926e+10 Pr: 142747(9.33386e+13); Du: 0(4.4089e-05) 1887.0s
     602021     4.8004888455e+10 Pr: 56036(1.3127e+13); Du: 0(4.41913e-05) 1943.3s
     625986     4.9236812003e+10 Pr: 28046(5.8317e+11); Du: 0(4.2946e-05) 1996.5s
     644751     5.0258581806e+10 Pr: 23691(8.78524e+10); Du: 0(4.56949e-05) 2046.5s
     666832     5.0897467209e+10 Pr: 13809(5.45239e+10); Du: 0(4.66778e-05) 2100.0s
     687302     5.1578867265e+10 Pr: 69929(7.88127e+13); Du: 0(5.17173e-05) 2153.2s
     706362     5.2054926967e+10 Pr: 30108(5.53258e+11); Du: 0(5.27365e-05) 2207.6s
     725955     5.2577214853e+10 Pr: 55687(2.87529e+12); Du: 0(5.31733e-05) 2261.1s
     743457     5.2935657512e+10 Pr: 14426(5.23359e+10); Du: 0(5.34234e-05) 2311.6s
     763559     5.3448548251e+10 Pr: 59699(1.65588e+12); Du: 0(5.37335e-05) 2363.6s
     783451     5.4119811540e+10 Pr: 37188(3.98177e+11); Du: 0(5.88059e-05) 2418.7s
     804917     5.4483092045e+10 Pr: 115809(5.51326e+13); Du: 0(6.09355e-05) 2476.7s
     825764     5.4850794693e+10 Pr: 20464(6.11151e+10); Du: 0(6.10043e-05) 2529.4s
     847412     5.5308512700e+10 Pr: 120420(1.03373e+13); Du: 0(6.26665e-05) 2582.5s
     869828     5.5625902195e+10 Pr: 109513(4.11369e+12); Du: 0(6.24111e-05) 2634.7s
     895882     5.6072627271e+10 Pr: 68353(1.79701e+12); Du: 0(6.26561e-05) 2689.3s
     918806     5.6369812991e+10 Pr: 96279(1.78712e+12); Du: 0(6.50731e-05) 2745.2s
     936498     5.6767726956e+10 Pr: 18886(1.54606e+11); Du: 0(6.61368e-05) 2796.2s
     963880     5.6978173962e+10 Pr: 13252(6.2226e+10); Du: 0(6.5512e-05) 2849.2s
     984719     5.7401878827e+10 Pr: 16504(1.9333e+11); Du: 0(6.55077e-05) 2904.0s
    1011752     5.7477885854e+10 Pr: 15914(8.42587e+10); Du: 0(6.7856e-05) 2956.5s
    1030869     5.7607933965e+10 Pr: 15637(6.75095e+10); Du: 0(6.98471e-05) 3006.7s
    1045063     5.7704923525e+10 Pr: 55924(1.57465e+12); Du: 0(6.47791e-05) 3061.4s
    1059057     5.7756787454e+10 Pr: 25547(1.32395e+11); Du: 0(6.4369e-05) 3112.7s
    1069509     5.7765128887e+10 Pr: 0(0); Du: 0(2.93718e-11) 3157.3s

Performed postsolve
Solving the original LP from the solution after postsolve

Model name          : linopy-problem-1h14k83x
Model status        : Optimal
Simplex   iterations: 1069509
Objective value     :  5.7765128887e+10
P-D objective error :  3.2622803506e-14
HiGHS run time      :       3159.62

INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 350424 primals, 814705 duals
Objective: 5.78e+10
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-ext-p-lower, Generator-ext-p-upper, Line-ext-s-lower, Line-ext-s-upper, StorageUnit-ext-p_dispatch-lower, StorageUnit-ext-p_dispatch-upper, StorageUnit-ext-p_store-lower, StorageUnit-ext-p_store-upper, StorageUnit-ext-state_of_charge-lower, StorageUnit-ext-state_of_charge-upper, Kirchhoff-Voltage-Law, StorageUnit-energy_balance were not assigned to the network.

('ok', 'optimal')

In [264]:
print(network.objective / 1e9)

57.765128887026606

In [265]:
network.statistics.optimal_capacity().div(1e3)  # GW
# or more detailed:
network.generators.p_nom_opt.div(1e3)           # GW, generators only

name
wind_Nord    125.514253
pv_Nord       21.241012
OCGT_Nord      0.311721
wind_West     -0.000000
pv_West       -0.000000
OCGT_West     11.310230
wind_Ost      -0.000000
pv_Ost        -0.000000
OCGT_Ost       9.360813
wind_Süd      -0.000000
pv_Süd       161.191678
OCGT_Süd      14.693515
Name: p_nom_opt, dtype: float64

In [266]:
network.statistics.energy_balance().sort_values().div(1e6)  # TWh

component    carrier          bus_carrier
Load         electricity      electricity   -1882.306915
StorageUnit  battery storage  electricity     -21.506243
Generator    OCGT             electricity     180.798450
             pv               electricity     860.457854
             wind             electricity     862.556855
dtype: float64

In [267]:
tsc = pd.concat({
    "capex": network.statistics.capex(),
    "opex":  network.statistics.opex(),
}, axis=1).div(1e9).round(2)  # bn€/a
print(tsc)

                             capex   opex
component   carrier
Generator   OCGT              2.33  13.62
            pv               14.19   0.01
            wind             18.50   1.56
StorageUnit battery storage   7.56    NaN

In [268]:
emissions = (
    network.generators_t.p
    / network.generators.efficiency
    * network.generators.carrier.map(network.carriers.co2_emissions)
)
print(emissions.sum().sum() / 1e6)  # total Mt CO2/a

8.94952326713398

In [269]:
network.statistics.energy_balance.iplot()